-- Migration: 00048_ai_economist.sql
-- Description: Tables for the Gemini AI Economist to store economy state, logs, and social feed.

-- 1. economy_state
-- Stores the current active multipliers set by the AI. We only need one active row, but we can store history or just update a singleton.
CREATE TABLE IF NOT EXISTS public.economy_state (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    match_reward_multiplier NUMERIC(4, 2) NOT NULL DEFAULT 1.00,
    medical_cost_multiplier NUMERIC(4, 2) NOT NULL DEFAULT 1.00,
    stadium_tax_multiplier NUMERIC(4, 2) NOT NULL DEFAULT 1.00,
    scouting_cost_multiplier NUMERIC(4, 2) NOT NULL DEFAULT 1.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert initial default row
INSERT INTO public.economy_state (match_reward_multiplier, medical_cost_multiplier, stadium_tax_multiplier, scouting_cost_multiplier)
VALUES (1.00, 1.00, 1.00, 1.00);

-- 2. economy_logs
-- Stores daily snapshots of the economy for the AI to analyze.
CREATE TABLE IF NOT EXISTS public.economy_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    log_date DATE NOT NULL UNIQUE,
    total_fc_in_circulation BIGINT NOT NULL DEFAULT 0,
    total_fc_minted_today BIGINT NOT NULL DEFAULT 0,
    total_fc_burned_today BIGINT NOT NULL DEFAULT 0,
    active_users_today INT NOT NULL DEFAULT 0,
    ai_reasoning TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. social_feed
-- Stores news articles generated by the AI (or system).
CREATE TABLE IF NOT EXISTS public.social_feed (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    author VARCHAR(100) NOT NULL DEFAULT 'League Central Bank',
    type VARCHAR(50) NOT NULL DEFAULT 'economy', -- 'economy', 'update', 'event'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add RLS Policies
ALTER TABLE public.economy_state ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users on economy_state" ON public.economy_state FOR SELECT USING (true);

ALTER TABLE public.economy_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users on economy_logs" ON public.economy_logs FOR SELECT USING (true);

ALTER TABLE public.social_feed ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users on social_feed" ON public.social_feed FOR SELECT USING (true);
